### ISSUE TITLE
Auth redirection issue

### ISSUE THREAD

**Issue by Boufel** [zync/zync-c4d#3]
Hello,

i faced an issue when connecting to Zync on browser, with the OAuth 2.0, this is the redirection link that i got : 

http://localhost:58700/Callback?code=4/awBsx5ni1c8DONOWjuVqo31DWk7bpp-_Mlw08BMYm_T1gYp9bjvalelKYxH6SFVAq1H2y7DtcdwJQwvmEZtwLzM

**Comment by molerus** [comment]
Hi Karin, can you elaborate on your workflow? What was exactly that you tried to do?

**Comment by Boufel** [comment]
So, choosed to Render with Zync from the "Pipeline" Menu, the browser is opened to login to Zync, the redirection is pointing to this URL.

**Comment by molerus** [comment]
This is a standard OAuth flow. The app that makes an authorization attempt opens a port on your local machine (in your case 58700) to receive a callback with the authorization token. In normal circumstances the browser should pass the token and close the window, so it must be some sort of a flake which either prevented the plugin from opening the port or at some point of the authorization it went away. Please verify your firewall settings, they may prevent the app from opening ports.
